### ISSUE TITLE
Hi Josh

### ISSUE THREAD

**Issue by aristotheme** [joshboyan/minframe#1]
When I write "95%" in html

I got this: 

95./builds/dev/

Could you help me please

**Comment by joshboyan** [comment]
"%" is a reserved character in minframe because that is what the compiler looks for to replace file paths. To use the percentage sign in your HTML; use the HTML entity  **&#37;**

**Comment by aristotheme** [comment]
ahh thank you very much Josh :)

**Comment by joshboyan** [comment]
You are very welcome! What do you think of minframe so far?

**Comment by aristotheme** [comment]
It is very useful tool for me.. exactly what i want for my project.. after it is done I like to share my project with you.

Thank you very much your awesome tool again :)

**Comment by joshboyan** [comment]
I am excited to see what you have made;)
